#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanHang")]
	public partial class QuanLyBanHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchi_tiet_hoa_don(chi_tiet_hoa_don instance);
    partial void Updatechi_tiet_hoa_don(chi_tiet_hoa_don instance);
    partial void Deletechi_tiet_hoa_don(chi_tiet_hoa_don instance);
    partial void Insertsan_pham(san_pham instance);
    partial void Updatesan_pham(san_pham instance);
    partial void Deletesan_pham(san_pham instance);
    partial void Insertchi_tiet_phieu_nhap(chi_tiet_phieu_nhap instance);
    partial void Updatechi_tiet_phieu_nhap(chi_tiet_phieu_nhap instance);
    partial void Deletechi_tiet_phieu_nhap(chi_tiet_phieu_nhap instance);
    partial void Insertdanh_gia(danh_gia instance);
    partial void Updatedanh_gia(danh_gia instance);
    partial void Deletedanh_gia(danh_gia instance);
    partial void Inserthoa_don(hoa_don instance);
    partial void Updatehoa_don(hoa_don instance);
    partial void Deletehoa_don(hoa_don instance);
    partial void Insertkhach_hang(khach_hang instance);
    partial void Updatekhach_hang(khach_hang instance);
    partial void Deletekhach_hang(khach_hang instance);
    partial void Insertkhuyen_mai(khuyen_mai instance);
    partial void Updatekhuyen_mai(khuyen_mai instance);
    partial void Deletekhuyen_mai(khuyen_mai instance);
    partial void Insertloai_nhan_vien(loai_nhan_vien instance);
    partial void Updateloai_nhan_vien(loai_nhan_vien instance);
    partial void Deleteloai_nhan_vien(loai_nhan_vien instance);
    partial void Insertloai_san_pham(loai_san_pham instance);
    partial void Updateloai_san_pham(loai_san_pham instance);
    partial void Deleteloai_san_pham(loai_san_pham instance);
    partial void Insertnhan_vien(nhan_vien instance);
    partial void Updatenhan_vien(nhan_vien instance);
    partial void Deletenhan_vien(nhan_vien instance);
    partial void Insertphan_hoi(phan_hoi instance);
    partial void Updatephan_hoi(phan_hoi instance);
    partial void Deletephan_hoi(phan_hoi instance);
    partial void Insertphieu_nhap(phieu_nhap instance);
    partial void Updatephieu_nhap(phieu_nhap instance);
    partial void Deletephieu_nhap(phieu_nhap instance);
    #endregion
		
		public QuanLyBanHangDataContext() : 
				base(global::DTO.Properties.Settings.Default.QuanLyBanHangConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBanHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBanHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBanHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBanHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chi_tiet_hoa_don> chi_tiet_hoa_dons
		{
			get
			{
				return this.GetTable<chi_tiet_hoa_don>();
			}
		}
		
		public System.Data.Linq.Table<san_pham> san_phams
		{
			get
			{
				return this.GetTable<san_pham>();
			}
		}
		
		public System.Data.Linq.Table<chi_tiet_phieu_nhap> chi_tiet_phieu_nhaps
		{
			get
			{
				return this.GetTable<chi_tiet_phieu_nhap>();
			}
		}
		
		public System.Data.Linq.Table<danh_gia> danh_gias
		{
			get
			{
				return this.GetTable<danh_gia>();
			}
		}
		
		public System.Data.Linq.Table<hoa_don> hoa_dons
		{
			get
			{
				return this.GetTable<hoa_don>();
			}
		}
		
		public System.Data.Linq.Table<khach_hang> khach_hangs
		{
			get
			{
				return this.GetTable<khach_hang>();
			}
		}
		
		public System.Data.Linq.Table<khuyen_mai> khuyen_mais
		{
			get
			{
				return this.GetTable<khuyen_mai>();
			}
		}
		
		public System.Data.Linq.Table<loai_nhan_vien> loai_nhan_viens
		{
			get
			{
				return this.GetTable<loai_nhan_vien>();
			}
		}
		
		public System.Data.Linq.Table<loai_san_pham> loai_san_phams
		{
			get
			{
				return this.GetTable<loai_san_pham>();
			}
		}
		
		public System.Data.Linq.Table<nhan_vien> nhan_viens
		{
			get
			{
				return this.GetTable<nhan_vien>();
			}
		}
		
		public System.Data.Linq.Table<phan_hoi> phan_hois
		{
			get
			{
				return this.GetTable<phan_hoi>();
			}
		}
		
		public System.Data.Linq.Table<phieu_nhap> phieu_nhaps
		{
			get
			{
				return this.GetTable<phieu_nhap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chi_tiet_hoa_don")]
	public partial class chi_tiet_hoa_don : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_hoa_don;
		
		private string _id_san_pham;
		
		private System.Nullable<int> _so_luong;
		
		private System.Nullable<double> _don_gia;
		
		private System.Nullable<double> _thanh_tien;
		
		private EntityRef<san_pham> _san_pham;
		
		private EntityRef<hoa_don> _hoa_don;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hoa_donChanging(string value);
    partial void Onid_hoa_donChanged();
    partial void Onid_san_phamChanging(string value);
    partial void Onid_san_phamChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    partial void Ondon_giaChanging(System.Nullable<double> value);
    partial void Ondon_giaChanged();
    partial void Onthanh_tienChanging(System.Nullable<double> value);
    partial void Onthanh_tienChanged();
    #endregion
		
		public chi_tiet_hoa_don()
		{
			this._san_pham = default(EntityRef<san_pham>);
			this._hoa_don = default(EntityRef<hoa_don>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoa_don", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_hoa_don
		{
			get
			{
				return this._id_hoa_don;
			}
			set
			{
				if ((this._id_hoa_don != value))
				{
					if (this._hoa_don.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_hoa_donChanging(value);
					this.SendPropertyChanging();
					this._id_hoa_don = value;
					this.SendPropertyChanged("id_hoa_don");
					this.Onid_hoa_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_san_pham", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_san_pham
		{
			get
			{
				return this._id_san_pham;
			}
			set
			{
				if ((this._id_san_pham != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_san_pham = value;
					this.SendPropertyChanged("id_san_pham");
					this.Onid_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_gia", DbType="Float")]
		public System.Nullable<double> don_gia
		{
			get
			{
				return this._don_gia;
			}
			set
			{
				if ((this._don_gia != value))
				{
					this.Ondon_giaChanging(value);
					this.SendPropertyChanging();
					this._don_gia = value;
					this.SendPropertyChanged("don_gia");
					this.Ondon_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_tien", DbType="Float")]
		public System.Nullable<double> thanh_tien
		{
			get
			{
				return this._thanh_tien;
			}
			set
			{
				if ((this._thanh_tien != value))
				{
					this.Onthanh_tienChanging(value);
					this.SendPropertyChanging();
					this._thanh_tien = value;
					this.SendPropertyChanged("thanh_tien");
					this.Onthanh_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_chi_tiet_hoa_don", Storage="_san_pham", ThisKey="id_san_pham", OtherKey="id_san_pham", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.chi_tiet_hoa_dons.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_hoa_dons.Add(this);
						this._id_san_pham = value.id_san_pham;
					}
					else
					{
						this._id_san_pham = default(string);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_chi_tiet_hoa_don", Storage="_hoa_don", ThisKey="id_hoa_don", OtherKey="id_hoa_don", IsForeignKey=true)]
		public hoa_don hoa_don
		{
			get
			{
				return this._hoa_don.Entity;
			}
			set
			{
				hoa_don previousValue = this._hoa_don.Entity;
				if (((previousValue != value) 
							|| (this._hoa_don.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoa_don.Entity = null;
						previousValue.chi_tiet_hoa_dons.Remove(this);
					}
					this._hoa_don.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_hoa_dons.Add(this);
						this._id_hoa_don = value.id_hoa_don;
					}
					else
					{
						this._id_hoa_don = default(string);
					}
					this.SendPropertyChanged("hoa_don");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.san_pham")]
	public partial class san_pham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_san_pham;
		
		private string _ten_san_pham;
		
		private System.Nullable<double> _don_gia;
		
		private System.Nullable<double> _diem;
		
		private string _hinh;
		
		private string _mo_ta;
		
		private string _id_loai;
		
		private System.Nullable<int> _so_luong_ton;
		
		private EntitySet<chi_tiet_hoa_don> _chi_tiet_hoa_dons;
		
		private EntitySet<chi_tiet_phieu_nhap> _chi_tiet_phieu_nhaps;
		
		private EntitySet<danh_gia> _danh_gias;
		
		private EntitySet<khuyen_mai> _khuyen_mais;
		
		private EntitySet<phan_hoi> _phan_hois;
		
		private EntityRef<loai_san_pham> _loai_san_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_san_phamChanging(string value);
    partial void Onid_san_phamChanged();
    partial void Onten_san_phamChanging(string value);
    partial void Onten_san_phamChanged();
    partial void Ondon_giaChanging(System.Nullable<double> value);
    partial void Ondon_giaChanged();
    partial void OndiemChanging(System.Nullable<double> value);
    partial void OndiemChanged();
    partial void OnhinhChanging(string value);
    partial void OnhinhChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Onid_loaiChanging(string value);
    partial void Onid_loaiChanged();
    partial void Onso_luong_tonChanging(System.Nullable<int> value);
    partial void Onso_luong_tonChanged();
    #endregion
		
		public san_pham()
		{
			this._chi_tiet_hoa_dons = new EntitySet<chi_tiet_hoa_don>(new Action<chi_tiet_hoa_don>(this.attach_chi_tiet_hoa_dons), new Action<chi_tiet_hoa_don>(this.detach_chi_tiet_hoa_dons));
			this._chi_tiet_phieu_nhaps = new EntitySet<chi_tiet_phieu_nhap>(new Action<chi_tiet_phieu_nhap>(this.attach_chi_tiet_phieu_nhaps), new Action<chi_tiet_phieu_nhap>(this.detach_chi_tiet_phieu_nhaps));
			this._danh_gias = new EntitySet<danh_gia>(new Action<danh_gia>(this.attach_danh_gias), new Action<danh_gia>(this.detach_danh_gias));
			this._khuyen_mais = new EntitySet<khuyen_mai>(new Action<khuyen_mai>(this.attach_khuyen_mais), new Action<khuyen_mai>(this.detach_khuyen_mais));
			this._phan_hois = new EntitySet<phan_hoi>(new Action<phan_hoi>(this.attach_phan_hois), new Action<phan_hoi>(this.detach_phan_hois));
			this._loai_san_pham = default(EntityRef<loai_san_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_san_pham", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_san_pham
		{
			get
			{
				return this._id_san_pham;
			}
			set
			{
				if ((this._id_san_pham != value))
				{
					this.Onid_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_san_pham = value;
					this.SendPropertyChanged("id_san_pham");
					this.Onid_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_san_pham", DbType="NVarChar(200)")]
		public string ten_san_pham
		{
			get
			{
				return this._ten_san_pham;
			}
			set
			{
				if ((this._ten_san_pham != value))
				{
					this.Onten_san_phamChanging(value);
					this.SendPropertyChanging();
					this._ten_san_pham = value;
					this.SendPropertyChanged("ten_san_pham");
					this.Onten_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_gia", DbType="Float")]
		public System.Nullable<double> don_gia
		{
			get
			{
				return this._don_gia;
			}
			set
			{
				if ((this._don_gia != value))
				{
					this.Ondon_giaChanging(value);
					this.SendPropertyChanging();
					this._don_gia = value;
					this.SendPropertyChanged("don_gia");
					this.Ondon_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem", DbType="Float")]
		public System.Nullable<double> diem
		{
			get
			{
				return this._diem;
			}
			set
			{
				if ((this._diem != value))
				{
					this.OndiemChanging(value);
					this.SendPropertyChanging();
					this._diem = value;
					this.SendPropertyChanged("diem");
					this.OndiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh", DbType="NVarChar(500)")]
		public string hinh
		{
			get
			{
				return this._hinh;
			}
			set
			{
				if ((this._hinh != value))
				{
					this.OnhinhChanging(value);
					this.SendPropertyChanging();
					this._hinh = value;
					this.SendPropertyChanged("hinh");
					this.OnhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(500)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai", DbType="NVarChar(36)")]
		public string id_loai
		{
			get
			{
				return this._id_loai;
			}
			set
			{
				if ((this._id_loai != value))
				{
					if (this._loai_san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_loaiChanging(value);
					this.SendPropertyChanging();
					this._id_loai = value;
					this.SendPropertyChanged("id_loai");
					this.Onid_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong_ton", DbType="Int")]
		public System.Nullable<int> so_luong_ton
		{
			get
			{
				return this._so_luong_ton;
			}
			set
			{
				if ((this._so_luong_ton != value))
				{
					this.Onso_luong_tonChanging(value);
					this.SendPropertyChanging();
					this._so_luong_ton = value;
					this.SendPropertyChanged("so_luong_ton");
					this.Onso_luong_tonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_chi_tiet_hoa_don", Storage="_chi_tiet_hoa_dons", ThisKey="id_san_pham", OtherKey="id_san_pham")]
		public EntitySet<chi_tiet_hoa_don> chi_tiet_hoa_dons
		{
			get
			{
				return this._chi_tiet_hoa_dons;
			}
			set
			{
				this._chi_tiet_hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_chi_tiet_phieu_nhap", Storage="_chi_tiet_phieu_nhaps", ThisKey="id_san_pham", OtherKey="id_san_pham")]
		public EntitySet<chi_tiet_phieu_nhap> chi_tiet_phieu_nhaps
		{
			get
			{
				return this._chi_tiet_phieu_nhaps;
			}
			set
			{
				this._chi_tiet_phieu_nhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_danh_gia", Storage="_danh_gias", ThisKey="id_san_pham", OtherKey="id_san_pham")]
		public EntitySet<danh_gia> danh_gias
		{
			get
			{
				return this._danh_gias;
			}
			set
			{
				this._danh_gias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_khuyen_mai", Storage="_khuyen_mais", ThisKey="id_san_pham", OtherKey="id_san_pham")]
		public EntitySet<khuyen_mai> khuyen_mais
		{
			get
			{
				return this._khuyen_mais;
			}
			set
			{
				this._khuyen_mais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_phan_hoi", Storage="_phan_hois", ThisKey="id_san_pham", OtherKey="id_san_pham")]
		public EntitySet<phan_hoi> phan_hois
		{
			get
			{
				return this._phan_hois;
			}
			set
			{
				this._phan_hois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loai_san_pham_san_pham", Storage="_loai_san_pham", ThisKey="id_loai", OtherKey="id_loai", IsForeignKey=true)]
		public loai_san_pham loai_san_pham
		{
			get
			{
				return this._loai_san_pham.Entity;
			}
			set
			{
				loai_san_pham previousValue = this._loai_san_pham.Entity;
				if (((previousValue != value) 
							|| (this._loai_san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loai_san_pham.Entity = null;
						previousValue.san_phams.Remove(this);
					}
					this._loai_san_pham.Entity = value;
					if ((value != null))
					{
						value.san_phams.Add(this);
						this._id_loai = value.id_loai;
					}
					else
					{
						this._id_loai = default(string);
					}
					this.SendPropertyChanged("loai_san_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chi_tiet_hoa_dons(chi_tiet_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_chi_tiet_hoa_dons(chi_tiet_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
		
		private void attach_chi_tiet_phieu_nhaps(chi_tiet_phieu_nhap entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_chi_tiet_phieu_nhaps(chi_tiet_phieu_nhap entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
		
		private void attach_danh_gias(danh_gia entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_danh_gias(danh_gia entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
		
		private void attach_khuyen_mais(khuyen_mai entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_khuyen_mais(khuyen_mai entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
		
		private void attach_phan_hois(phan_hoi entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_phan_hois(phan_hoi entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chi_tiet_phieu_nhap")]
	public partial class chi_tiet_phieu_nhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_phieu_nhap;
		
		private string _id_san_pham;
		
		private System.Nullable<int> _so_luong;
		
		private System.Nullable<double> _don_gia;
		
		private System.Nullable<double> _thanh_tien;
		
		private EntityRef<san_pham> _san_pham;
		
		private EntityRef<phieu_nhap> _phieu_nhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phieu_nhapChanging(string value);
    partial void Onid_phieu_nhapChanged();
    partial void Onid_san_phamChanging(string value);
    partial void Onid_san_phamChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    partial void Ondon_giaChanging(System.Nullable<double> value);
    partial void Ondon_giaChanged();
    partial void Onthanh_tienChanging(System.Nullable<double> value);
    partial void Onthanh_tienChanged();
    #endregion
		
		public chi_tiet_phieu_nhap()
		{
			this._san_pham = default(EntityRef<san_pham>);
			this._phieu_nhap = default(EntityRef<phieu_nhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phieu_nhap", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_phieu_nhap
		{
			get
			{
				return this._id_phieu_nhap;
			}
			set
			{
				if ((this._id_phieu_nhap != value))
				{
					if (this._phieu_nhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_phieu_nhapChanging(value);
					this.SendPropertyChanging();
					this._id_phieu_nhap = value;
					this.SendPropertyChanged("id_phieu_nhap");
					this.Onid_phieu_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_san_pham", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_san_pham
		{
			get
			{
				return this._id_san_pham;
			}
			set
			{
				if ((this._id_san_pham != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_san_pham = value;
					this.SendPropertyChanged("id_san_pham");
					this.Onid_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_gia", DbType="Float")]
		public System.Nullable<double> don_gia
		{
			get
			{
				return this._don_gia;
			}
			set
			{
				if ((this._don_gia != value))
				{
					this.Ondon_giaChanging(value);
					this.SendPropertyChanging();
					this._don_gia = value;
					this.SendPropertyChanged("don_gia");
					this.Ondon_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_tien", DbType="Float")]
		public System.Nullable<double> thanh_tien
		{
			get
			{
				return this._thanh_tien;
			}
			set
			{
				if ((this._thanh_tien != value))
				{
					this.Onthanh_tienChanging(value);
					this.SendPropertyChanging();
					this._thanh_tien = value;
					this.SendPropertyChanged("thanh_tien");
					this.Onthanh_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_chi_tiet_phieu_nhap", Storage="_san_pham", ThisKey="id_san_pham", OtherKey="id_san_pham", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.chi_tiet_phieu_nhaps.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_phieu_nhaps.Add(this);
						this._id_san_pham = value.id_san_pham;
					}
					else
					{
						this._id_san_pham = default(string);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieu_nhap_chi_tiet_phieu_nhap", Storage="_phieu_nhap", ThisKey="id_phieu_nhap", OtherKey="id_phieu_nhap", IsForeignKey=true)]
		public phieu_nhap phieu_nhap
		{
			get
			{
				return this._phieu_nhap.Entity;
			}
			set
			{
				phieu_nhap previousValue = this._phieu_nhap.Entity;
				if (((previousValue != value) 
							|| (this._phieu_nhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phieu_nhap.Entity = null;
						previousValue.chi_tiet_phieu_nhaps.Remove(this);
					}
					this._phieu_nhap.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_phieu_nhaps.Add(this);
						this._id_phieu_nhap = value.id_phieu_nhap;
					}
					else
					{
						this._id_phieu_nhap = default(string);
					}
					this.SendPropertyChanged("phieu_nhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danh_gia")]
	public partial class danh_gia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_danh_gia;
		
		private string _noi_dung_danh_gia;
		
		private System.Nullable<int> _diem;
		
		private System.Nullable<System.DateTime> _ngay_danh_gia;
		
		private string _id_khach_hang;
		
		private string _id_san_pham;
		
		private EntityRef<san_pham> _san_pham;
		
		private EntityRef<khach_hang> _khach_hang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_danh_giaChanging(string value);
    partial void Onid_danh_giaChanged();
    partial void Onnoi_dung_danh_giaChanging(string value);
    partial void Onnoi_dung_danh_giaChanged();
    partial void OndiemChanging(System.Nullable<int> value);
    partial void OndiemChanged();
    partial void Onngay_danh_giaChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_danh_giaChanged();
    partial void Onid_khach_hangChanging(string value);
    partial void Onid_khach_hangChanged();
    partial void Onid_san_phamChanging(string value);
    partial void Onid_san_phamChanged();
    #endregion
		
		public danh_gia()
		{
			this._san_pham = default(EntityRef<san_pham>);
			this._khach_hang = default(EntityRef<khach_hang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danh_gia", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_danh_gia
		{
			get
			{
				return this._id_danh_gia;
			}
			set
			{
				if ((this._id_danh_gia != value))
				{
					this.Onid_danh_giaChanging(value);
					this.SendPropertyChanging();
					this._id_danh_gia = value;
					this.SendPropertyChanged("id_danh_gia");
					this.Onid_danh_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noi_dung_danh_gia", DbType="NVarChar(200)")]
		public string noi_dung_danh_gia
		{
			get
			{
				return this._noi_dung_danh_gia;
			}
			set
			{
				if ((this._noi_dung_danh_gia != value))
				{
					this.Onnoi_dung_danh_giaChanging(value);
					this.SendPropertyChanging();
					this._noi_dung_danh_gia = value;
					this.SendPropertyChanged("noi_dung_danh_gia");
					this.Onnoi_dung_danh_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem", DbType="Int")]
		public System.Nullable<int> diem
		{
			get
			{
				return this._diem;
			}
			set
			{
				if ((this._diem != value))
				{
					this.OndiemChanging(value);
					this.SendPropertyChanging();
					this._diem = value;
					this.SendPropertyChanged("diem");
					this.OndiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_danh_gia", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_danh_gia
		{
			get
			{
				return this._ngay_danh_gia;
			}
			set
			{
				if ((this._ngay_danh_gia != value))
				{
					this.Onngay_danh_giaChanging(value);
					this.SendPropertyChanging();
					this._ngay_danh_gia = value;
					this.SendPropertyChanged("ngay_danh_gia");
					this.Onngay_danh_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khach_hang", DbType="NVarChar(36)")]
		public string id_khach_hang
		{
			get
			{
				return this._id_khach_hang;
			}
			set
			{
				if ((this._id_khach_hang != value))
				{
					if (this._khach_hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._id_khach_hang = value;
					this.SendPropertyChanged("id_khach_hang");
					this.Onid_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_san_pham", DbType="NVarChar(36)")]
		public string id_san_pham
		{
			get
			{
				return this._id_san_pham;
			}
			set
			{
				if ((this._id_san_pham != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_san_pham = value;
					this.SendPropertyChanged("id_san_pham");
					this.Onid_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_danh_gia", Storage="_san_pham", ThisKey="id_san_pham", OtherKey="id_san_pham", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.danh_gias.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.danh_gias.Add(this);
						this._id_san_pham = value.id_san_pham;
					}
					else
					{
						this._id_san_pham = default(string);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hang_danh_gia", Storage="_khach_hang", ThisKey="id_khach_hang", OtherKey="id_khach_hang", IsForeignKey=true)]
		public khach_hang khach_hang
		{
			get
			{
				return this._khach_hang.Entity;
			}
			set
			{
				khach_hang previousValue = this._khach_hang.Entity;
				if (((previousValue != value) 
							|| (this._khach_hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khach_hang.Entity = null;
						previousValue.danh_gias.Remove(this);
					}
					this._khach_hang.Entity = value;
					if ((value != null))
					{
						value.danh_gias.Add(this);
						this._id_khach_hang = value.id_khach_hang;
					}
					else
					{
						this._id_khach_hang = default(string);
					}
					this.SendPropertyChanged("khach_hang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoa_don")]
	public partial class hoa_don : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_hoa_don;
		
		private string _id_khach_hang;
		
		private System.Nullable<System.DateTime> _ngay_dat;
		
		private System.Nullable<System.DateTime> _ngay_giao_hang;
		
		private System.Nullable<int> _tinh_trang_thanh_toan;
		
		private System.Nullable<int> _phuong_thuc_thanh_toan;
		
		private System.Nullable<int> _tinh_trang_giao_hang;
		
		private System.Nullable<double> _tong_tien;
		
		private EntitySet<chi_tiet_hoa_don> _chi_tiet_hoa_dons;
		
		private EntityRef<khach_hang> _khach_hang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hoa_donChanging(string value);
    partial void Onid_hoa_donChanged();
    partial void Onid_khach_hangChanging(string value);
    partial void Onid_khach_hangChanged();
    partial void Onngay_datChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_datChanged();
    partial void Onngay_giao_hangChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_giao_hangChanged();
    partial void Ontinh_trang_thanh_toanChanging(System.Nullable<int> value);
    partial void Ontinh_trang_thanh_toanChanged();
    partial void Onphuong_thuc_thanh_toanChanging(System.Nullable<int> value);
    partial void Onphuong_thuc_thanh_toanChanged();
    partial void Ontinh_trang_giao_hangChanging(System.Nullable<int> value);
    partial void Ontinh_trang_giao_hangChanged();
    partial void Ontong_tienChanging(System.Nullable<double> value);
    partial void Ontong_tienChanged();
    #endregion
		
		public hoa_don()
		{
			this._chi_tiet_hoa_dons = new EntitySet<chi_tiet_hoa_don>(new Action<chi_tiet_hoa_don>(this.attach_chi_tiet_hoa_dons), new Action<chi_tiet_hoa_don>(this.detach_chi_tiet_hoa_dons));
			this._khach_hang = default(EntityRef<khach_hang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoa_don", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_hoa_don
		{
			get
			{
				return this._id_hoa_don;
			}
			set
			{
				if ((this._id_hoa_don != value))
				{
					this.Onid_hoa_donChanging(value);
					this.SendPropertyChanging();
					this._id_hoa_don = value;
					this.SendPropertyChanged("id_hoa_don");
					this.Onid_hoa_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khach_hang", DbType="NVarChar(36)")]
		public string id_khach_hang
		{
			get
			{
				return this._id_khach_hang;
			}
			set
			{
				if ((this._id_khach_hang != value))
				{
					if (this._khach_hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._id_khach_hang = value;
					this.SendPropertyChanged("id_khach_hang");
					this.Onid_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_dat", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_dat
		{
			get
			{
				return this._ngay_dat;
			}
			set
			{
				if ((this._ngay_dat != value))
				{
					this.Onngay_datChanging(value);
					this.SendPropertyChanging();
					this._ngay_dat = value;
					this.SendPropertyChanged("ngay_dat");
					this.Onngay_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_giao_hang", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_giao_hang
		{
			get
			{
				return this._ngay_giao_hang;
			}
			set
			{
				if ((this._ngay_giao_hang != value))
				{
					this.Onngay_giao_hangChanging(value);
					this.SendPropertyChanging();
					this._ngay_giao_hang = value;
					this.SendPropertyChanged("ngay_giao_hang");
					this.Onngay_giao_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinh_trang_thanh_toan", DbType="Int")]
		public System.Nullable<int> tinh_trang_thanh_toan
		{
			get
			{
				return this._tinh_trang_thanh_toan;
			}
			set
			{
				if ((this._tinh_trang_thanh_toan != value))
				{
					this.Ontinh_trang_thanh_toanChanging(value);
					this.SendPropertyChanging();
					this._tinh_trang_thanh_toan = value;
					this.SendPropertyChanged("tinh_trang_thanh_toan");
					this.Ontinh_trang_thanh_toanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuong_thuc_thanh_toan", DbType="Int")]
		public System.Nullable<int> phuong_thuc_thanh_toan
		{
			get
			{
				return this._phuong_thuc_thanh_toan;
			}
			set
			{
				if ((this._phuong_thuc_thanh_toan != value))
				{
					this.Onphuong_thuc_thanh_toanChanging(value);
					this.SendPropertyChanging();
					this._phuong_thuc_thanh_toan = value;
					this.SendPropertyChanged("phuong_thuc_thanh_toan");
					this.Onphuong_thuc_thanh_toanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinh_trang_giao_hang", DbType="Int")]
		public System.Nullable<int> tinh_trang_giao_hang
		{
			get
			{
				return this._tinh_trang_giao_hang;
			}
			set
			{
				if ((this._tinh_trang_giao_hang != value))
				{
					this.Ontinh_trang_giao_hangChanging(value);
					this.SendPropertyChanging();
					this._tinh_trang_giao_hang = value;
					this.SendPropertyChanged("tinh_trang_giao_hang");
					this.Ontinh_trang_giao_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Float")]
		public System.Nullable<double> tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_chi_tiet_hoa_don", Storage="_chi_tiet_hoa_dons", ThisKey="id_hoa_don", OtherKey="id_hoa_don")]
		public EntitySet<chi_tiet_hoa_don> chi_tiet_hoa_dons
		{
			get
			{
				return this._chi_tiet_hoa_dons;
			}
			set
			{
				this._chi_tiet_hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hang_hoa_don", Storage="_khach_hang", ThisKey="id_khach_hang", OtherKey="id_khach_hang", IsForeignKey=true)]
		public khach_hang khach_hang
		{
			get
			{
				return this._khach_hang.Entity;
			}
			set
			{
				khach_hang previousValue = this._khach_hang.Entity;
				if (((previousValue != value) 
							|| (this._khach_hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khach_hang.Entity = null;
						previousValue.hoa_dons.Remove(this);
					}
					this._khach_hang.Entity = value;
					if ((value != null))
					{
						value.hoa_dons.Add(this);
						this._id_khach_hang = value.id_khach_hang;
					}
					else
					{
						this._id_khach_hang = default(string);
					}
					this.SendPropertyChanged("khach_hang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chi_tiet_hoa_dons(chi_tiet_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = this;
		}
		
		private void detach_chi_tiet_hoa_dons(chi_tiet_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khach_hang")]
	public partial class khach_hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_khach_hang;
		
		private string _ten_khach_hang;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private string _dia_chi;
		
		private string _email;
		
		private string _dien_thoai;
		
		private string _tai_khoan;
		
		private string _mat_khau;
		
		private string _dia_chi_giao_hang;
		
		private EntitySet<danh_gia> _danh_gias;
		
		private EntitySet<hoa_don> _hoa_dons;
		
		private EntitySet<phan_hoi> _phan_hois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_khach_hangChanging(string value);
    partial void Onid_khach_hangChanged();
    partial void Onten_khach_hangChanging(string value);
    partial void Onten_khach_hangChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondien_thoaiChanging(string value);
    partial void Ondien_thoaiChanged();
    partial void Ontai_khoanChanging(string value);
    partial void Ontai_khoanChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void Ondia_chi_giao_hangChanging(string value);
    partial void Ondia_chi_giao_hangChanged();
    #endregion
		
		public khach_hang()
		{
			this._danh_gias = new EntitySet<danh_gia>(new Action<danh_gia>(this.attach_danh_gias), new Action<danh_gia>(this.detach_danh_gias));
			this._hoa_dons = new EntitySet<hoa_don>(new Action<hoa_don>(this.attach_hoa_dons), new Action<hoa_don>(this.detach_hoa_dons));
			this._phan_hois = new EntitySet<phan_hoi>(new Action<phan_hoi>(this.attach_phan_hois), new Action<phan_hoi>(this.detach_phan_hois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khach_hang", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_khach_hang
		{
			get
			{
				return this._id_khach_hang;
			}
			set
			{
				if ((this._id_khach_hang != value))
				{
					this.Onid_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._id_khach_hang = value;
					this.SendPropertyChanged("id_khach_hang");
					this.Onid_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_khach_hang", DbType="NVarChar(200)")]
		public string ten_khach_hang
		{
			get
			{
				return this._ten_khach_hang;
			}
			set
			{
				if ((this._ten_khach_hang != value))
				{
					this.Onten_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._ten_khach_hang = value;
					this.SendPropertyChanged("ten_khach_hang");
					this.Onten_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(200)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(200)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dien_thoai", DbType="NVarChar(20)")]
		public string dien_thoai
		{
			get
			{
				return this._dien_thoai;
			}
			set
			{
				if ((this._dien_thoai != value))
				{
					this.Ondien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._dien_thoai = value;
					this.SendPropertyChanged("dien_thoai");
					this.Ondien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tai_khoan", DbType="NVarChar(200)")]
		public string tai_khoan
		{
			get
			{
				return this._tai_khoan;
			}
			set
			{
				if ((this._tai_khoan != value))
				{
					this.Ontai_khoanChanging(value);
					this.SendPropertyChanging();
					this._tai_khoan = value;
					this.SendPropertyChanged("tai_khoan");
					this.Ontai_khoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="NVarChar(200)")]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi_giao_hang", DbType="NVarChar(200)")]
		public string dia_chi_giao_hang
		{
			get
			{
				return this._dia_chi_giao_hang;
			}
			set
			{
				if ((this._dia_chi_giao_hang != value))
				{
					this.Ondia_chi_giao_hangChanging(value);
					this.SendPropertyChanging();
					this._dia_chi_giao_hang = value;
					this.SendPropertyChanged("dia_chi_giao_hang");
					this.Ondia_chi_giao_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hang_danh_gia", Storage="_danh_gias", ThisKey="id_khach_hang", OtherKey="id_khach_hang")]
		public EntitySet<danh_gia> danh_gias
		{
			get
			{
				return this._danh_gias;
			}
			set
			{
				this._danh_gias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hang_hoa_don", Storage="_hoa_dons", ThisKey="id_khach_hang", OtherKey="id_khach_hang")]
		public EntitySet<hoa_don> hoa_dons
		{
			get
			{
				return this._hoa_dons;
			}
			set
			{
				this._hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hang_phan_hoi", Storage="_phan_hois", ThisKey="id_khach_hang", OtherKey="id_khach_hang")]
		public EntitySet<phan_hoi> phan_hois
		{
			get
			{
				return this._phan_hois;
			}
			set
			{
				this._phan_hois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_danh_gias(danh_gia entity)
		{
			this.SendPropertyChanging();
			entity.khach_hang = this;
		}
		
		private void detach_danh_gias(danh_gia entity)
		{
			this.SendPropertyChanging();
			entity.khach_hang = null;
		}
		
		private void attach_hoa_dons(hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.khach_hang = this;
		}
		
		private void detach_hoa_dons(hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.khach_hang = null;
		}
		
		private void attach_phan_hois(phan_hoi entity)
		{
			this.SendPropertyChanging();
			entity.khach_hang = this;
		}
		
		private void detach_phan_hois(phan_hoi entity)
		{
			this.SendPropertyChanging();
			entity.khach_hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khuyen_mai")]
	public partial class khuyen_mai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_khuyen_mai;
		
		private string _ten_khuyen_mai;
		
		private string _noi_dung_khuyen_mai;
		
		private System.Nullable<int> _phan_tram_khuyen_mai;
		
		private string _id_san_pham;
		
		private EntityRef<san_pham> _san_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_khuyen_maiChanging(string value);
    partial void Onid_khuyen_maiChanged();
    partial void Onten_khuyen_maiChanging(string value);
    partial void Onten_khuyen_maiChanged();
    partial void Onnoi_dung_khuyen_maiChanging(string value);
    partial void Onnoi_dung_khuyen_maiChanged();
    partial void Onphan_tram_khuyen_maiChanging(System.Nullable<int> value);
    partial void Onphan_tram_khuyen_maiChanged();
    partial void Onid_san_phamChanging(string value);
    partial void Onid_san_phamChanged();
    #endregion
		
		public khuyen_mai()
		{
			this._san_pham = default(EntityRef<san_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khuyen_mai", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_khuyen_mai
		{
			get
			{
				return this._id_khuyen_mai;
			}
			set
			{
				if ((this._id_khuyen_mai != value))
				{
					this.Onid_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._id_khuyen_mai = value;
					this.SendPropertyChanged("id_khuyen_mai");
					this.Onid_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_khuyen_mai", DbType="NVarChar(200)")]
		public string ten_khuyen_mai
		{
			get
			{
				return this._ten_khuyen_mai;
			}
			set
			{
				if ((this._ten_khuyen_mai != value))
				{
					this.Onten_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._ten_khuyen_mai = value;
					this.SendPropertyChanged("ten_khuyen_mai");
					this.Onten_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noi_dung_khuyen_mai", DbType="NVarChar(200)")]
		public string noi_dung_khuyen_mai
		{
			get
			{
				return this._noi_dung_khuyen_mai;
			}
			set
			{
				if ((this._noi_dung_khuyen_mai != value))
				{
					this.Onnoi_dung_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._noi_dung_khuyen_mai = value;
					this.SendPropertyChanged("noi_dung_khuyen_mai");
					this.Onnoi_dung_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phan_tram_khuyen_mai", DbType="Int")]
		public System.Nullable<int> phan_tram_khuyen_mai
		{
			get
			{
				return this._phan_tram_khuyen_mai;
			}
			set
			{
				if ((this._phan_tram_khuyen_mai != value))
				{
					this.Onphan_tram_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._phan_tram_khuyen_mai = value;
					this.SendPropertyChanged("phan_tram_khuyen_mai");
					this.Onphan_tram_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_san_pham", DbType="NVarChar(36)")]
		public string id_san_pham
		{
			get
			{
				return this._id_san_pham;
			}
			set
			{
				if ((this._id_san_pham != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_san_pham = value;
					this.SendPropertyChanged("id_san_pham");
					this.Onid_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_khuyen_mai", Storage="_san_pham", ThisKey="id_san_pham", OtherKey="id_san_pham", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.khuyen_mais.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.khuyen_mais.Add(this);
						this._id_san_pham = value.id_san_pham;
					}
					else
					{
						this._id_san_pham = default(string);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loai_nhan_vien")]
	public partial class loai_nhan_vien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_loai_nhan_vien;
		
		private string _ten_loai_nhan_vien;
		
		private EntitySet<nhan_vien> _nhan_viens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_loai_nhan_vienChanging(string value);
    partial void Onid_loai_nhan_vienChanged();
    partial void Onten_loai_nhan_vienChanging(string value);
    partial void Onten_loai_nhan_vienChanged();
    #endregion
		
		public loai_nhan_vien()
		{
			this._nhan_viens = new EntitySet<nhan_vien>(new Action<nhan_vien>(this.attach_nhan_viens), new Action<nhan_vien>(this.detach_nhan_viens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai_nhan_vien", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_loai_nhan_vien
		{
			get
			{
				return this._id_loai_nhan_vien;
			}
			set
			{
				if ((this._id_loai_nhan_vien != value))
				{
					this.Onid_loai_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._id_loai_nhan_vien = value;
					this.SendPropertyChanged("id_loai_nhan_vien");
					this.Onid_loai_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai_nhan_vien", DbType="NVarChar(200)")]
		public string ten_loai_nhan_vien
		{
			get
			{
				return this._ten_loai_nhan_vien;
			}
			set
			{
				if ((this._ten_loai_nhan_vien != value))
				{
					this.Onten_loai_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ten_loai_nhan_vien = value;
					this.SendPropertyChanged("ten_loai_nhan_vien");
					this.Onten_loai_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loai_nhan_vien_nhan_vien", Storage="_nhan_viens", ThisKey="id_loai_nhan_vien", OtherKey="id_loai_nhan_vien")]
		public EntitySet<nhan_vien> nhan_viens
		{
			get
			{
				return this._nhan_viens;
			}
			set
			{
				this._nhan_viens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhan_viens(nhan_vien entity)
		{
			this.SendPropertyChanging();
			entity.loai_nhan_vien = this;
		}
		
		private void detach_nhan_viens(nhan_vien entity)
		{
			this.SendPropertyChanging();
			entity.loai_nhan_vien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loai_san_pham")]
	public partial class loai_san_pham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_loai;
		
		private string _ten_loai;
		
		private string _hinh;
		
		private EntitySet<san_pham> _san_phams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_loaiChanging(string value);
    partial void Onid_loaiChanged();
    partial void Onten_loaiChanging(string value);
    partial void Onten_loaiChanged();
    partial void OnhinhChanging(string value);
    partial void OnhinhChanged();
    #endregion
		
		public loai_san_pham()
		{
			this._san_phams = new EntitySet<san_pham>(new Action<san_pham>(this.attach_san_phams), new Action<san_pham>(this.detach_san_phams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_loai
		{
			get
			{
				return this._id_loai;
			}
			set
			{
				if ((this._id_loai != value))
				{
					this.Onid_loaiChanging(value);
					this.SendPropertyChanging();
					this._id_loai = value;
					this.SendPropertyChanged("id_loai");
					this.Onid_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai", DbType="NVarChar(200)")]
		public string ten_loai
		{
			get
			{
				return this._ten_loai;
			}
			set
			{
				if ((this._ten_loai != value))
				{
					this.Onten_loaiChanging(value);
					this.SendPropertyChanging();
					this._ten_loai = value;
					this.SendPropertyChanged("ten_loai");
					this.Onten_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh", DbType="NVarChar(200)")]
		public string hinh
		{
			get
			{
				return this._hinh;
			}
			set
			{
				if ((this._hinh != value))
				{
					this.OnhinhChanging(value);
					this.SendPropertyChanging();
					this._hinh = value;
					this.SendPropertyChanged("hinh");
					this.OnhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loai_san_pham_san_pham", Storage="_san_phams", ThisKey="id_loai", OtherKey="id_loai")]
		public EntitySet<san_pham> san_phams
		{
			get
			{
				return this._san_phams;
			}
			set
			{
				this._san_phams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_san_phams(san_pham entity)
		{
			this.SendPropertyChanging();
			entity.loai_san_pham = this;
		}
		
		private void detach_san_phams(san_pham entity)
		{
			this.SendPropertyChanging();
			entity.loai_san_pham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhan_vien")]
	public partial class nhan_vien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_nhan_vien;
		
		private string _ten_nhan_vien;
		
		private string _tai_khoan;
		
		private string _mat_khau;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private string _dia_chi;
		
		private string _dien_thoai;
		
		private string _chuc_vu;
		
		private string _id_loai_nhan_vien;
		
		private EntitySet<phieu_nhap> _phieu_nhaps;
		
		private EntityRef<loai_nhan_vien> _loai_nhan_vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhan_vienChanging(string value);
    partial void Onid_nhan_vienChanged();
    partial void Onten_nhan_vienChanging(string value);
    partial void Onten_nhan_vienChanged();
    partial void Ontai_khoanChanging(string value);
    partial void Ontai_khoanChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Ondien_thoaiChanging(string value);
    partial void Ondien_thoaiChanged();
    partial void Onchuc_vuChanging(string value);
    partial void Onchuc_vuChanged();
    partial void Onid_loai_nhan_vienChanging(string value);
    partial void Onid_loai_nhan_vienChanged();
    #endregion
		
		public nhan_vien()
		{
			this._phieu_nhaps = new EntitySet<phieu_nhap>(new Action<phieu_nhap>(this.attach_phieu_nhaps), new Action<phieu_nhap>(this.detach_phieu_nhaps));
			this._loai_nhan_vien = default(EntityRef<loai_nhan_vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhan_vien", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_nhan_vien
		{
			get
			{
				return this._id_nhan_vien;
			}
			set
			{
				if ((this._id_nhan_vien != value))
				{
					this.Onid_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._id_nhan_vien = value;
					this.SendPropertyChanged("id_nhan_vien");
					this.Onid_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nhan_vien", DbType="NVarChar(200)")]
		public string ten_nhan_vien
		{
			get
			{
				return this._ten_nhan_vien;
			}
			set
			{
				if ((this._ten_nhan_vien != value))
				{
					this.Onten_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ten_nhan_vien = value;
					this.SendPropertyChanged("ten_nhan_vien");
					this.Onten_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tai_khoan", DbType="NVarChar(200)")]
		public string tai_khoan
		{
			get
			{
				return this._tai_khoan;
			}
			set
			{
				if ((this._tai_khoan != value))
				{
					this.Ontai_khoanChanging(value);
					this.SendPropertyChanging();
					this._tai_khoan = value;
					this.SendPropertyChanged("tai_khoan");
					this.Ontai_khoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="NVarChar(200)")]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(200)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dien_thoai", DbType="NVarChar(20)")]
		public string dien_thoai
		{
			get
			{
				return this._dien_thoai;
			}
			set
			{
				if ((this._dien_thoai != value))
				{
					this.Ondien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._dien_thoai = value;
					this.SendPropertyChanged("dien_thoai");
					this.Ondien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuc_vu", DbType="NVarChar(200)")]
		public string chuc_vu
		{
			get
			{
				return this._chuc_vu;
			}
			set
			{
				if ((this._chuc_vu != value))
				{
					this.Onchuc_vuChanging(value);
					this.SendPropertyChanging();
					this._chuc_vu = value;
					this.SendPropertyChanged("chuc_vu");
					this.Onchuc_vuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai_nhan_vien", DbType="NVarChar(36)")]
		public string id_loai_nhan_vien
		{
			get
			{
				return this._id_loai_nhan_vien;
			}
			set
			{
				if ((this._id_loai_nhan_vien != value))
				{
					if (this._loai_nhan_vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_loai_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._id_loai_nhan_vien = value;
					this.SendPropertyChanged("id_loai_nhan_vien");
					this.Onid_loai_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhan_vien_phieu_nhap", Storage="_phieu_nhaps", ThisKey="id_nhan_vien", OtherKey="id_nhan_vien")]
		public EntitySet<phieu_nhap> phieu_nhaps
		{
			get
			{
				return this._phieu_nhaps;
			}
			set
			{
				this._phieu_nhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loai_nhan_vien_nhan_vien", Storage="_loai_nhan_vien", ThisKey="id_loai_nhan_vien", OtherKey="id_loai_nhan_vien", IsForeignKey=true)]
		public loai_nhan_vien loai_nhan_vien
		{
			get
			{
				return this._loai_nhan_vien.Entity;
			}
			set
			{
				loai_nhan_vien previousValue = this._loai_nhan_vien.Entity;
				if (((previousValue != value) 
							|| (this._loai_nhan_vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loai_nhan_vien.Entity = null;
						previousValue.nhan_viens.Remove(this);
					}
					this._loai_nhan_vien.Entity = value;
					if ((value != null))
					{
						value.nhan_viens.Add(this);
						this._id_loai_nhan_vien = value.id_loai_nhan_vien;
					}
					else
					{
						this._id_loai_nhan_vien = default(string);
					}
					this.SendPropertyChanged("loai_nhan_vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieu_nhaps(phieu_nhap entity)
		{
			this.SendPropertyChanging();
			entity.nhan_vien = this;
		}
		
		private void detach_phieu_nhaps(phieu_nhap entity)
		{
			this.SendPropertyChanging();
			entity.nhan_vien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phan_hoi")]
	public partial class phan_hoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_phan_hoi;
		
		private string _noi_dung_phan_hoi;
		
		private System.Nullable<System.DateTime> _ngay_phan_hoi;
		
		private string _id_khach_hang;
		
		private string _id_san_pham;
		
		private EntityRef<khach_hang> _khach_hang;
		
		private EntityRef<san_pham> _san_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phan_hoiChanging(string value);
    partial void Onid_phan_hoiChanged();
    partial void Onnoi_dung_phan_hoiChanging(string value);
    partial void Onnoi_dung_phan_hoiChanged();
    partial void Onngay_phan_hoiChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_phan_hoiChanged();
    partial void Onid_khach_hangChanging(string value);
    partial void Onid_khach_hangChanged();
    partial void Onid_san_phamChanging(string value);
    partial void Onid_san_phamChanged();
    #endregion
		
		public phan_hoi()
		{
			this._khach_hang = default(EntityRef<khach_hang>);
			this._san_pham = default(EntityRef<san_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phan_hoi", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_phan_hoi
		{
			get
			{
				return this._id_phan_hoi;
			}
			set
			{
				if ((this._id_phan_hoi != value))
				{
					this.Onid_phan_hoiChanging(value);
					this.SendPropertyChanging();
					this._id_phan_hoi = value;
					this.SendPropertyChanged("id_phan_hoi");
					this.Onid_phan_hoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noi_dung_phan_hoi", DbType="NVarChar(500)")]
		public string noi_dung_phan_hoi
		{
			get
			{
				return this._noi_dung_phan_hoi;
			}
			set
			{
				if ((this._noi_dung_phan_hoi != value))
				{
					this.Onnoi_dung_phan_hoiChanging(value);
					this.SendPropertyChanging();
					this._noi_dung_phan_hoi = value;
					this.SendPropertyChanged("noi_dung_phan_hoi");
					this.Onnoi_dung_phan_hoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_phan_hoi", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_phan_hoi
		{
			get
			{
				return this._ngay_phan_hoi;
			}
			set
			{
				if ((this._ngay_phan_hoi != value))
				{
					this.Onngay_phan_hoiChanging(value);
					this.SendPropertyChanging();
					this._ngay_phan_hoi = value;
					this.SendPropertyChanged("ngay_phan_hoi");
					this.Onngay_phan_hoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khach_hang", DbType="NVarChar(36)")]
		public string id_khach_hang
		{
			get
			{
				return this._id_khach_hang;
			}
			set
			{
				if ((this._id_khach_hang != value))
				{
					if (this._khach_hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._id_khach_hang = value;
					this.SendPropertyChanged("id_khach_hang");
					this.Onid_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_san_pham", DbType="NVarChar(36)")]
		public string id_san_pham
		{
			get
			{
				return this._id_san_pham;
			}
			set
			{
				if ((this._id_san_pham != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_san_pham = value;
					this.SendPropertyChanged("id_san_pham");
					this.Onid_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hang_phan_hoi", Storage="_khach_hang", ThisKey="id_khach_hang", OtherKey="id_khach_hang", IsForeignKey=true)]
		public khach_hang khach_hang
		{
			get
			{
				return this._khach_hang.Entity;
			}
			set
			{
				khach_hang previousValue = this._khach_hang.Entity;
				if (((previousValue != value) 
							|| (this._khach_hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khach_hang.Entity = null;
						previousValue.phan_hois.Remove(this);
					}
					this._khach_hang.Entity = value;
					if ((value != null))
					{
						value.phan_hois.Add(this);
						this._id_khach_hang = value.id_khach_hang;
					}
					else
					{
						this._id_khach_hang = default(string);
					}
					this.SendPropertyChanged("khach_hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_phan_hoi", Storage="_san_pham", ThisKey="id_san_pham", OtherKey="id_san_pham", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.phan_hois.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.phan_hois.Add(this);
						this._id_san_pham = value.id_san_pham;
					}
					else
					{
						this._id_san_pham = default(string);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieu_nhap")]
	public partial class phieu_nhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_phieu_nhap;
		
		private System.Nullable<System.DateTime> _ngay_nhap;
		
		private string _id_nhan_vien;
		
		private System.Nullable<double> _tong_tien;
		
		private string _ghi_chu;
		
		private EntitySet<chi_tiet_phieu_nhap> _chi_tiet_phieu_nhaps;
		
		private EntityRef<nhan_vien> _nhan_vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phieu_nhapChanging(string value);
    partial void Onid_phieu_nhapChanged();
    partial void Onngay_nhapChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_nhapChanged();
    partial void Onid_nhan_vienChanging(string value);
    partial void Onid_nhan_vienChanged();
    partial void Ontong_tienChanging(System.Nullable<double> value);
    partial void Ontong_tienChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    #endregion
		
		public phieu_nhap()
		{
			this._chi_tiet_phieu_nhaps = new EntitySet<chi_tiet_phieu_nhap>(new Action<chi_tiet_phieu_nhap>(this.attach_chi_tiet_phieu_nhaps), new Action<chi_tiet_phieu_nhap>(this.detach_chi_tiet_phieu_nhaps));
			this._nhan_vien = default(EntityRef<nhan_vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phieu_nhap", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_phieu_nhap
		{
			get
			{
				return this._id_phieu_nhap;
			}
			set
			{
				if ((this._id_phieu_nhap != value))
				{
					this.Onid_phieu_nhapChanging(value);
					this.SendPropertyChanging();
					this._id_phieu_nhap = value;
					this.SendPropertyChanged("id_phieu_nhap");
					this.Onid_phieu_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_nhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_nhap
		{
			get
			{
				return this._ngay_nhap;
			}
			set
			{
				if ((this._ngay_nhap != value))
				{
					this.Onngay_nhapChanging(value);
					this.SendPropertyChanging();
					this._ngay_nhap = value;
					this.SendPropertyChanged("ngay_nhap");
					this.Onngay_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhan_vien", DbType="NVarChar(36)")]
		public string id_nhan_vien
		{
			get
			{
				return this._id_nhan_vien;
			}
			set
			{
				if ((this._id_nhan_vien != value))
				{
					if (this._nhan_vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._id_nhan_vien = value;
					this.SendPropertyChanged("id_nhan_vien");
					this.Onid_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Float")]
		public System.Nullable<double> tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(500)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieu_nhap_chi_tiet_phieu_nhap", Storage="_chi_tiet_phieu_nhaps", ThisKey="id_phieu_nhap", OtherKey="id_phieu_nhap")]
		public EntitySet<chi_tiet_phieu_nhap> chi_tiet_phieu_nhaps
		{
			get
			{
				return this._chi_tiet_phieu_nhaps;
			}
			set
			{
				this._chi_tiet_phieu_nhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhan_vien_phieu_nhap", Storage="_nhan_vien", ThisKey="id_nhan_vien", OtherKey="id_nhan_vien", IsForeignKey=true)]
		public nhan_vien nhan_vien
		{
			get
			{
				return this._nhan_vien.Entity;
			}
			set
			{
				nhan_vien previousValue = this._nhan_vien.Entity;
				if (((previousValue != value) 
							|| (this._nhan_vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhan_vien.Entity = null;
						previousValue.phieu_nhaps.Remove(this);
					}
					this._nhan_vien.Entity = value;
					if ((value != null))
					{
						value.phieu_nhaps.Add(this);
						this._id_nhan_vien = value.id_nhan_vien;
					}
					else
					{
						this._id_nhan_vien = default(string);
					}
					this.SendPropertyChanged("nhan_vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chi_tiet_phieu_nhaps(chi_tiet_phieu_nhap entity)
		{
			this.SendPropertyChanging();
			entity.phieu_nhap = this;
		}
		
		private void detach_chi_tiet_phieu_nhaps(chi_tiet_phieu_nhap entity)
		{
			this.SendPropertyChanging();
			entity.phieu_nhap = null;
		}
	}
}
#pragma warning restore 1591
